name: Install dependencies and canopy
description: "Installs Poetry, dependencies and optionally canopy library"
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.9"
  install-canopy:
    description: "Whether to install canopy library, or dependencies only"
    required: true
    default: "true"
  extras:
    description: "Extra dependencies to install, space separated"
    required: false
    default: "cohere transformers"

runs:
  using: "composite"
  steps:
  - name: Install Poetry
    uses: snok/install-poetry@v1
    with:
      version: 1.3.2
      virtualenvs-create: true
      virtualenvs-in-project: true
      installer-parallel: true
  #----------------------------------------------
  #       load cached venv if cache exists
  #----------------------------------------------
  - name: Load cached venv
    id: cached-poetry-dependencies
    uses: actions/cache@v3
    with:
      path: |
        .venv
        poetry.lock
      key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}
  #----------------------------------------------
  # install dependencies if cache does not exist
  #----------------------------------------------
  - name: Install dependencies
    shell: bash
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    env:
      CANOPY_EXTRAS: ${{ inputs.extras }}
    run: poetry install --no-interaction --no-root --with dev --extras "${CANOPY_EXTRAS}"
  - name: Install project
    if: ${{ inputs.install-canopy == 'true' }}
    shell: bash
    env:
      CANOPY_EXTRAS: ${{ inputs.extras }}
    run: make install-extras
