name: 🐞 Bug
description: Report a bug or an issue you've found
title: "[Bug] <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is this a new bug?
      description: >
        In other words: Is this an error, flaw, failure or fault? Please search issues to see if someone has already reported the bug you encountered.
      options:
        - label: I believe this is a new bug
          required: true
        - label: I have searched the existing issues, and I could not find an existing issue for this bug
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        If applicable, log output to help explain your problem.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Language version**: Python 3.9.12 (`python3 --version`)
          - **Canopy version**: 0.2 (`canopy --version`)
      value: |
        - **OS**:
        - **Language version**:
        - **Canopy version**:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

    validations:
      required: false
