blank_issues_enabled: true
contact_links:
  - name: 🤔 Ask a Question
    url: 'https://github.com/pinecone-io/canopy/discussions/new?category=q-a'
    about: Ask a question about how to use Canopy using GitHub discussions

