name: 'Release'

on:
  workflow_dispatch:
    inputs:
      releaseLevel:
        description: 'Release level'
        required: true
        type: choice
        default: 'patch'
        options:
          - 'patch' # bug fixes
          - 'minor' # new features, backwards compatible
          - 'major' # breaking changes
      generateBranch:
        description: 'Whether to generate a release branch'
        required: true
        type: boolean
        default: false
      generateTag:
        description: 'Whether to generate a release tag'
        required: true
        type: boolean
        default: true
  push:

env:
  PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
  PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # The lowest we support

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Bump version
        id: bump
        run: |
          poetry version ${{ inputs.releaseLevel || 'patch' }}
          echo "new_version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Build wheel
        run: |
          poetry build

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/

  test-all-OSes:
    if: false
    needs: build
    uses: ./.github/workflows/pre-release-CI.yml

  publish:
#    needs: [build, test-all-OSes]
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: download wheels
        uses: actions/download-artifact@v2
        with:
          path: ./dist/

      - name: Set version
        env:
          NEW_VERSION: ${{ needs.build.outputs.new_version }}
        run: |
          echo $NEW_VERSION
          poetry version $NEW_VERSION

      - name: Commit version update
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "relevance@pinecone.io"
          git add pyproject.toml
          git commit -m "Bump version to $(poetry version -s)"
          git push 

#      - name: Create tag
#        if: ${{ github.event_name == 'workflow_dispatch' && inputs.generateTag == 'true' }}
#        run: |
#          git tag -a $(poetry version -s) -m "V$(poetry version -s)"
#          git push origin "V$(poetry version -s)"

      - name: Create release branch
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.generateBranch == 'true' }}
        run: |
          git checkout -b release/$(poetry version -s)
          git push origin release/$(poetry version -s)

      - name: Create release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: "V$(poetry version -s)"
          release_name: $(poetry version -s)
